import type { CookProgram, GrillModel } from "./types";

export const GRILL_MODELS: GrillModel[] = [
  {
    id: "PB0820SPW",
    name: "Sportsman 820 Wi-Fi",
    series: "Sportsman",
    area: "820 in²",
    hopperLb: 21,
    probes: 2,
    wifi: true,
  },
];

export const PROGRAMS: CookProgram[] = [
  {
    id: "brisket",
    name: "Overnight Brisket",
    cut: "Packer brisket",
    setpoint: 225,
    pSetting: 4,
    probeTarget: 203,
    hours: "10–14 hr",
    wood: "Oak + hickory",
    blurb: "Low and slow until probe-tender. Expect a stall around 160–170°F — leave it alone.",
    probeMass: 1,
    stallLow: 155,
    stallHigh: 172,
    probe1Name: "Flat",
    probe2Name: "Point",
    stages: [
      {
        name: "Smoke",
        durationMin: 360,
        setpoint: 225,
        pSetting: 4,
        note: "Fat cap up. No peeking.",
        probeTarget: 165,
      },
      {
        name: "Through the stall",
        durationMin: 240,
        setpoint: 225,
        pSetting: 4,
        note: "Wrap in butcher paper when the bark is set.",
        probeTarget: 203,
      },
      {
        name: "Rest",
        durationMin: 90,
        setpoint: 170,
        pSetting: 6,
        note: "Hold in a cooler, towel-wrapped, at least 1 hour.",
        probeTarget: 203,
      },
    ],
  },
  {
    id: "pork-butt",
    name: "Pork Shoulder",
    cut: "Boston butt",
    setpoint: 250,
    pSetting: 4,
    probeTarget: 205,
    hours: "8–12 hr",
    wood: "Hickory + cherry",
    blurb: "Pull-apart pork. Probe the thickest part; it is done when it slides like butter.",
    probeMass: 0.9,
    stallLow: 150,
    stallHigh: 168,
    probe1Name: "Center",
    probe2Name: "Shoulder",
    stages: [
      {
        name: "Bark",
        durationMin: 300,
        setpoint: 250,
        pSetting: 4,
        note: "Spritz with apple cider after 3 hours if the surface looks dry.",
        probeTarget: 165,
      },
      {
        name: "Wrap & finish",
        durationMin: 240,
        setpoint: 250,
        pSetting: 5,
        note: "Wrap tight. Finish to 203–205°F.",
        probeTarget: 205,
      },
    ],
  },
  {
    id: "ribs-321",
    name: "Spare Ribs 3-2-1",
    cut: "Spare ribs",
    setpoint: 225,
    pSetting: 4,
    probeTarget: 195,
    hours: "6 hr",
    wood: "Cherry + apple",
    blurb: "Classic 3 hours smoke, 2 wrapped, 1 sauced and set.",
    probeMass: 0.45,
    stallLow: 148,
    stallHigh: 160,
    probe1Name: "Rack A",
    probe2Name: "Rack B",
    stages: [
      {
        name: "3 — Smoke",
        durationMin: 180,
        setpoint: 225,
        pSetting: 3,
        note: "Bone side down. Light dusting of rub.",
      },
      {
        name: "2 — Wrap",
        durationMin: 120,
        setpoint: 225,
        pSetting: 5,
        note: "Wrap with a pad of butter and a splash of apple juice.",
      },
      {
        name: "1 — Sauce",
        durationMin: 60,
        setpoint: 250,
        pSetting: 4,
        note: "Unwrap, sauce, and let it tack up.",
        probeTarget: 195,
      },
    ],
  },
  {
    id: "baby-backs",
    name: "Baby Backs 2-2-1",
    cut: "Baby back ribs",
    setpoint: 225,
    pSetting: 4,
    probeTarget: 190,
    hours: "5 hr",
    wood: "Apple",
    blurb: "Shorter 2-2-1 for leaner backs. Bend test over probe temp.",
    probeMass: 0.4,
    stallLow: 145,
    stallHigh: 158,
    probe1Name: "Rack A",
    probe2Name: "Rack B",
    stages: [
      {
        name: "2 — Smoke",
        durationMin: 120,
        setpoint: 225,
        pSetting: 3,
        note: "Remove the membrane.",
      },
      {
        name: "2 — Wrap",
        durationMin: 120,
        setpoint: 225,
        pSetting: 5,
        note: "Brown sugar and honey in the wrap.",
      },
      {
        name: "1 — Set",
        durationMin: 60,
        setpoint: 250,
        pSetting: 4,
        note: "Sauce in the last 20 minutes if you want glaze.",
        probeTarget: 190,
      },
    ],
  },
  {
    id: "chicken",
    name: "Spatchcock Chicken",
    cut: "Whole bird",
    setpoint: 375,
    pSetting: 5,
    probeTarget: 165,
    hours: "1–1.5 hr",
    wood: "Pecan",
    blurb: "Hot enough for crisp skin. Breast to 160, thighs to 175 — carryover does the rest.",
    probeMass: 0.35,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Breast",
    probe2Name: "Thigh",
    stages: [
      {
        name: "Roast",
        durationMin: 75,
        setpoint: 375,
        pSetting: 5,
        note: "Spatchcock, dry the skin, salt early.",
        probeTarget: 165,
      },
    ],
  },
  {
    id: "turkey",
    name: "Thanksgiving Turkey",
    cut: "Whole turkey",
    setpoint: 325,
    pSetting: 4,
    probeTarget: 165,
    hours: "3–4 hr",
    wood: "Apple + pecan",
    blurb: "325°F keeps the breast from drying. Pull at 160 in the breast.",
    probeMass: 0.7,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Breast",
    probe2Name: "Thigh",
    stages: [
      {
        name: "Smoke-roast",
        durationMin: 210,
        setpoint: 325,
        pSetting: 4,
        note: "Spatchcock if it fits. Butter under the skin.",
        probeTarget: 165,
      },
    ],
  },
  {
    id: "salmon",
    name: "Smoked Salmon",
    cut: "Side of salmon",
    setpoint: 225,
    pSetting: 2,
    probeTarget: 135,
    hours: "1–2 hr",
    wood: "Alder",
    blurb: "Gentle smoke. Pull at 135°F for moist flakes — 145 if you want it firmer.",
    probeMass: 0.25,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Thick end",
    probe2Name: "Center",
    stages: [
      {
        name: "Smoke",
        durationMin: 90,
        setpoint: 225,
        pSetting: 2,
        note: "Pat dry. A thin pellicle from a fridge rest helps the smoke stick.",
        probeTarget: 135,
      },
    ],
  },
  {
    id: "wings",
    name: "Crispy Wings",
    cut: "Party wings",
    setpoint: 375,
    pSetting: 6,
    probeTarget: 175,
    hours: "45–60 min",
    wood: "Hickory",
    blurb: "High heat, then sauce and flash. Probe is optional — look for tight skin.",
    probeMass: 0.2,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Drumette",
    probe2Name: "Flat",
    stages: [
      {
        name: "Render",
        durationMin: 40,
        setpoint: 375,
        pSetting: 6,
        note: "Baking powder in the rub for blistered skin.",
        probeTarget: 175,
      },
      {
        name: "Sauce",
        durationMin: 10,
        setpoint: 400,
        pSetting: 6,
        note: "Toss, then 8 minutes to set the glaze.",
      },
    ],
  },
  {
    id: "reverse-sear",
    name: "Reverse-Sear Steak",
    cut: "Thick ribeye / strip",
    setpoint: 225,
    pSetting: 4,
    probeTarget: 120,
    hours: "45–75 min",
    wood: "Oak",
    blurb: "Smoke to 10–15° below finish, rest, then lid-open sear at 500°F.",
    probeMass: 0.3,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Steak 1",
    probe2Name: "Steak 2",
    stages: [
      {
        name: "Smoke",
        durationMin: 50,
        setpoint: 225,
        pSetting: 4,
        note: "Pull 10–15° under your finish temp.",
        probeTarget: 120,
      },
      {
        name: "Sear",
        durationMin: 8,
        setpoint: 500,
        pSetting: 7,
        note: "Open the flame broiler if you have one. 90 seconds a side.",
      },
    ],
  },
  {
    id: "pizza",
    name: "Grill Pizza",
    cut: "Neapolitan-ish",
    setpoint: 450,
    pSetting: 7,
    probeTarget: null,
    hours: "8–12 min",
    wood: "Competition blend",
    blurb: "Stone on the grates, preheat 20 minutes. Probes stay out.",
    probeMass: 0.2,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Stone",
    probe2Name: "Dome",
    stages: [
      {
        name: "Preheat stone",
        durationMin: 20,
        setpoint: 450,
        pSetting: 7,
        note: "Lid down. Launch when the stone is ripping hot.",
      },
      {
        name: "Bake",
        durationMin: 10,
        setpoint: 500,
        pSetting: 7,
        note: "Rotate once. Pull when the leopard spots show.",
      },
    ],
  },
  {
    id: "smoke",
    name: "Cold-ish Smoke",
    cut: "Cheese, nuts, salt",
    setpoint: 180,
    pSetting: 2,
    probeTarget: null,
    hours: "1–3 hr",
    wood: "Apple, tiny puffs",
    blurb: "Pit Boss smoke setting lives around 180°F. Lower P-set means more pellets, more smoke.",
    probeMass: 0.15,
    stallLow: 0,
    stallHigh: 0,
    probe1Name: "Air",
    probe2Name: "Grate",
    stages: [
      {
        name: "Smoke",
        durationMin: 120,
        setpoint: 180,
        pSetting: 2,
        note: "P0–P2 for heavier smoke. Keep the hopper full — smoke cooks sip pellets slowly.",
      },
    ],
  },
  {
    id: "hot-fast",
    name: "Hot & Fast",
    cut: "Weeknight anything",
    setpoint: 350,
    pSetting: 6,
    probeTarget: 165,
    hours: "2–4 hr",
    wood: "Competition blend",
    blurb: "When you do not have 12 hours. Bark is different — still good.",
    probeMass: 0.7,
    stallLow: 158,
    stallHigh: 168,
    probe1Name: "Thick",
    probe2Name: "Thin",
    stages: [
      {
        name: "Run it hot",
        durationMin: 180,
        setpoint: 350,
        pSetting: 6,
        note: "Wrap earlier than a 225° cook. Watch the edges.",
        probeTarget: 200,
      },
    ],
  },
];

export function getProgram(id: string) {
  return PROGRAMS.find((p) => p.id === id) ?? null;
}

export function getModel(id: string) {
  return GRILL_MODELS.find((m) => m.id === id) ?? GRILL_MODELS[0];
}

export const SETPOINT_MIN = 180;
export const SETPOINT_MAX = 500;
export const SETPOINT_STEP = 5;
/** Smoke on the PBC board — P-set only works here. */
export const SMOKE_SETPOINT = 180;

/** Factory PBC board on the Sportsman 820. */
export const STOCK_BOARD_TEMPS = [180, 200, 225, 250, 300, 350, 400, 450, 475, 500];

export const PRESET_TEMPS = STOCK_BOARD_TEMPS;
